helmGlobals:
  chartHome: ../../../submodules/openstack-helm-infra

helmCharts:
  - name: ingress
    releaseName: ingress-openstack-internal
    valuesInline:
      deployment:
        cluster:
          class: nginx
    valuesFile: helm/ingress-helm-overrides.yaml
    namespace: openstack
