bases:
  - "../base"

patches:
  - target:
      kind: MariaDB
      name: mariadb-galera
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/galera/enabled
        value: false
