apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-system-endpoint-permissions
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-kube-system-endpoints
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: ovn-controller
  namespace: openstack
roleRef:
  kind: Role
  name: kube-system-endpoint-permissions
  apiGroup: rbac.authorization.k8s.io
