---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openvswitch-bin
data:
  openvswitch-db-server.sh: |
    #!/bin/bash
    set -ex
    COMMAND="${@:-start}"
    OVS_DB=/run/openvswitch/flex.db
    OVS_SCHEMA=/usr/share/openvswitch/vswitch.ovsschema
    OVS_PID=/run/openvswitch/ovsdb-flex-server.pid
    OVS_SOCKET=/run/openvswitch/flex.sock

    function start () {
      mkdir -p "$(dirname ${OVS_DB})"
      if [[ ! -e "${OVS_DB}" ]]; then
        ovsdb-tool create "${OVS_DB}"
      fi

      if [[ "$(ovsdb-tool needs-conversion ${OVS_DB} ${OVS_SCHEMA})" == 'yes' ]]; then
          ovsdb-tool convert ${OVS_DB} ${OVS_SCHEMA}
      fi

      umask 000
      exec /usr/sbin/ovsdb-server ${OVS_DB} \
              -vconsole:emer \
              -vconsole:err \
              -vconsole:info \
              --pidfile=${OVS_PID} \
              --remote=punix:${OVS_SOCKET} \
              --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
              --private-key=db:Open_vSwitch,SSL,private_key \
              --certificate=db:Open_vSwitch,SSL,certificate \
              --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert
    }

    function stop () {
      PID=$(cat $OVS_PID)
      ovs-appctl -T1 -t /run/openvswitch/ovsdb-server.${PID}.ctl exit
    }

    $COMMAND

  openvswitch-vswitchd.sh: |
    #!/bin/bash
    set -ex
    COMMAND="${@:-start}"
    OVS_SOCKET=/run/openvswitch/flex.sock
    OVS_PID=/run/openvswitch/ovs-flex-vswitchd.pid

    # Create vhostuser directory and grant nova user (default UID 42424) access
    # permissions.

    function start () {
      t=0
      while [ ! -e "${OVS_SOCKET}" ] ; do
          echo "waiting for ovs socket $sock"
          sleep 1
          t=$(($t+1))
          if [ $t -ge 10 ] ; then
              echo "no ovs socket, giving up"
              exit 1
          fi
      done

      ovs-vsctl --db=unix:${OVS_SOCKET} --no-wait show

      exec /usr/sbin/ovs-vswitchd unix:${OVS_SOCKET} \
              -vconsole:emer \
              -vconsole:err \
              -vconsole:info \
              --pidfile=${OVS_PID} \
              --mlockall
    }

    function stop () {
      PID=$(cat $OVS_PID)
      ovs-appctl -T1 -t /run/openvswitch/ovs-vswitchd.${PID}.ctl exit
    }

    find_latest_ctl_file() {
        latest_file=""
        latest_file=$(ls -lt /run/openvswitch/*.ctl | awk 'NR==1 {if ($3 == "root") print $NF}')

        echo "$latest_file"
    }

    function poststart () {
      # This enables the usage of 'ovs-appctl' from neutron-ovs-agent pod.

      # Wait for potential new ctl file before continuing
      timeout=5
      start_time=$(date +%s)
      while true; do
          latest_ctl_file=$(find_latest_ctl_file)
          if [ -n "$latest_ctl_file" ]; then
              break
          fi
          current_time=$(date +%s)
          if (( current_time - start_time >= timeout )); then
              break
          fi
          sleep 1
      done

      until [ -f $OVS_PID ]
      do
          echo "Waiting for file $OVS_PID"
          sleep 1
      done

      PID=$(cat $OVS_PID)
      OVS_CTL=/run/openvswitch/ovs-vswitchd.${PID}.ctl

      until [ -S $OVS_CTL ]
      do
          echo "Waiting for file $OVS_CTL"
          sleep 1
      done
      chown 42424.42424 ${OVS_CTL}

    }

    $COMMAND

  openvswitch-vswitchd-init-modules.sh: |
    #!/bin/bash
    set -ex
    chroot /mnt/host-rootfs modprobe openvswitch
    chroot /mnt/host-rootfs modprobe gre
    chroot /mnt/host-rootfs modprobe vxlan
---
# Source: openvswitch/templates/daemonset.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvswitch-server
  namespace: default
---
# Source: openvswitch/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openvswitch
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: openvswitch
    application: openvswitch
    component: server
spec:
  selector:
    matchLabels:
      release_group: openvswitch
      application: openvswitch
      component: server

  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        release_group: openvswitch
        application: openvswitch
        component: server
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
    spec:
      shareProcessNamespace: true
      serviceAccountName: openvswitch-server
      securityContext:
        runAsUser: 42424
      nodeSelector:
        openvswitch: enabled

      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:

        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
        - name: openvswitch-db-perms
          image: "docker.io/openstackhelm/openvswitch:latest-ubuntu_jammy"
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 0

          command:
            - chown
            - -R
            - "42424"
            - /run/openvswitch
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: run-openvswitch
              mountPath: /run/openvswitch
        - name: openvswitch-vswitchd-modules
          image: "docker.io/openstackhelm/openvswitch:latest-ubuntu_jammy"
          imagePullPolicy: IfNotPresent

          securityContext:
            capabilities:
              add:
              - SYS_MODULE
              - SYS_CHROOT
            readOnlyRootFilesystem: true
            runAsUser: 0
          command:
            - /tmp/openvswitch-vswitchd-init-modules.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-vswitchd-init-modules.sh
              subPath: openvswitch-vswitchd-init-modules.sh
              readOnly: true
            - name: host-rootfs
              mountPath: /mnt/host-rootfs
              mountPropagation: HostToContainer
              readOnly: true
      containers:
        - name: openvswitch-db
          image: "docker.io/openstackhelm/openvswitch:latest-ubuntu_jammy"
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 42424

          livenessProbe:
            exec:
              command:
              - /usr/bin/ovs-vsctl
              - show
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /usr/bin/ovs-vsctl
              - list
              - Open_Vswitch
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
          command:
            - /tmp/openvswitch-db-server.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/openvswitch-db-server.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-db-server.sh
              subPath: openvswitch-db-server.sh
              readOnly: true
            - name: run
              mountPath: /run
        - name: openvswitch-vswitchd
          image: "docker.io/openstackhelm/openvswitch:latest-ubuntu_jammy"
          imagePullPolicy: IfNotPresent

          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            readOnlyRootFilesystem: true
            runAsUser: 0

          # ensures this container can speak to the ovs database
          # successfully before its marked as ready
          livenessProbe:
            exec:
              command:
              - /usr/bin/ovs-appctl
              - bond/list
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /usr/bin/ovs-vsctl show
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 1
          command:
            - /tmp/openvswitch-vswitchd.sh
            - start
          lifecycle:
            postStart:
              exec:
                command:
                  - /tmp/openvswitch-vswitchd.sh
                  - poststart
            preStop:
              exec:
                command:
                  - /tmp/openvswitch-vswitchd.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-vswitchd.sh
              subPath: openvswitch-vswitchd.sh
              readOnly: true
            - name: run
              mountPath: /run
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: openvswitch-bin
          configMap:
            name: openvswitch-bin
            defaultMode: 0555
        - name: run
          hostPath:
            path: /run
            type: Directory
        - name: run-openvswitch
          hostPath:
            path: /run/openvswitch
            type: DirectoryOrCreate
        - name: host-rootfs
          hostPath:
            path: /
            type: Directory
