# TODO: Figure out how to make this work with the rabbitmq cluster and openstack
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-production-ready
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
