helmCharts:
  - name: memcached
    repo: https://marketplace.azurecr.io/helm/v1/repo
    releaseName: memcached
    valuesInline:
      architecture: high-availability
      autoscaling:
        enabled: true
    namespace: openstack
